[package]
name = "avocado-schema-derive"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "2.0.38"
quote = "1.0"
avocado-schema = { path = "../schema" }

[[test]]
name = "tests"
path = "tests/reflect.rs"
